# Generated by Django 4.2.17 on 2026-01-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
