# Generated by Django 6.0 on 2026-01-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insurancecompany", "0001_initial"),
        ("insurancetype", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_name", models.CharField(max_length=255)),
                ("policy_details", models.TextField()),
                ("coverage", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurancecompany.insurancecompany",
                    ),
                ),
                (
                    "insurance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurancetype.insurancetype",
                    ),
                ),
            ],
        ),
    ]
