# Generated by Django 6.0 on 2026-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default="default_password", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                default="default_password", max_length=15, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
