# Generated by Django 4.2.17 on 2026-01-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_profile_image"),
        ("customer", "0002_remove_customer_address_remove_customer_phone_and_more"),
    ]

    operations = []
